### ISSUE TITLE
No use of buffer

### ISSUE THREAD

**Issue by Julien00859** [Anthilam/StudentWork-SimpleSecurity#1]
Several file have very poor speed due to the lack of buffer.

One example is the following line

https://github.com/Anthilam/StudentWork-SimpleSecurity/blob/6aaa8007d748d52f3259e510b5b70ccd92571d4d/vigenere_encrypt.c#L41

`printf`ing each character is very slow, you could use a char buffer[256] instead and `printf("%s", buffer);` for each slice of 256 characters. Net performance upgrade is guaranteed :+1:

**Comment by TimG8** [comment]
Yup, old project mate, just dropping here for archiving purposes :D
